version: '3'
services:
    authenticator:
        build: authenticator
        image: dbauth_authenticator
        volumes:
            - .:/usr/src/dbauth
        entrypoint: ./authenticator
    sdk:
        build: sdk
        image: dbauth_sdk
        volumes:
            - .:/usr/src/dbauth
